config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace='account')),
    path('', include('hotel.urls', namespace='hotel')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [
    path('', views.home_page, name='home'),

    path('search-for-room/', views.search_for_room, name='search_for_room'),
    path('<slug:slug>/', views.hotel_detail_page, name='hotel_detail'),
    path('book-a-room/<slug:slug>/', views.book_a_room, name='book_a_room'),
]

hotel/models.py
from django.db import models
from multiselectfield import MultiSelectField
from autoslug import AutoSlugField
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from account.models import User



# Create your models here.



class Hotel(models.Model):
    feature_choices = (
        ('Dry cleaning','Dry cleaning'),
        
       
        ('Wifi', 'Wifi'),
        ('Room service', 'Room service'),
        ('Special service', 'Special service'),
        ('Waiting area', 'waiting area'),
        ('Secrete smoking area', 'Secrete smoking area'),
        ('Lift','Lift')
    )

    hotel_activities = (
        ('Spa','Spa'),
        ('Gym','Gym'),
        ('Car park', 'Car park'),
        ('Kids Play Area', 'Kids Play Area'),
    )

    hotel_payment_methods = (
        ('Credit Card', 'Credit Card'),
        ('Debit Card', 'Debit Card'),
        ('Cash', 'Cash'),
        ('Crypto', 'Crypto')
    )

    hotel_staff_languages = (
        ('English', 'English'),
        ('French', 'French'),
        ('German', 'German'),
        ('Portuguese', 'Portuguese')
    )

    name =  models.CharField(max_length=150)
    
    description = models.TextField()
    # room =  models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=False)
    address = models.CharField(max_length=250)
    image = models.ImageField(upload_to='room_images', null=True, blank=True)
    background_image = models.URLField(null=True, blank=True)
    city = models.CharField(max_length=100)
    services = MultiSelectField(choices=feature_choices, blank=True, max_length=200)
    activities = MultiSelectField(choices=hotel_activities, blank=True, max_length=200)
    payment_method = MultiSelectField(choices=hotel_payment_methods, blank=True, max_length=200)
    staff_languages = MultiSelectField(choices=hotel_staff_languages, blank=True, max_length=200)
    mobile_no = models.CharField( max_length=15)
    email = models.EmailField(max_length=50)
    slug = AutoSlugField(unique=True, populate_from='name',sep='-',null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class RoomType(models.Model):
     choices_for_rooms = (
        ('Wifi', 'Wifi'),
        ('Air Conditioning','Air Conditioning'),

    )

     first_room_img = models.ImageField(
        upload_to="room_images" ),

     second_room_img = models.ImageField(
        upload_to="room_images",
        null=True,
        blank=True),
     third_room_img = models.ImageField(
        upload_to="room_images",
        null=True,
        blank=True
    )
     name = models.CharField(max_length=100)
     description = models.TextField()
     room_options = MultiSelectField(choices=choices_for_rooms,blank=True, max_length=300)
     slug = AutoSlugField(unique=True, populate_from='name',sep='-',null=True)

     def __str__(self):
         return self.name
    
class Room(models.Model):
    choices_for_rooms = (
        ('Wifi', 'Wifi'),
        ('Air Conditioning','Air Conditioning'),
        ('TV', 'TV')

    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    hotel = models.ForeignKey(Hotel,on_delete=models.CASCADE, null=True)
    room_type = models.ForeignKey(RoomType, on_delete=models.PROTECT, null=True)
    price = models.IntegerField()
    room_options = MultiSelectField(choices=choices_for_rooms,blank=True, max_length=300)
    is_Booked = models.BooleanField(default=False,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(unique=True, populate_from='name',sep='-',null=True)

    def __str__(self):
        return f"{self.name} "
    







class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in_date = models.DateTimeField()
    check_out_date = models.DateTimeField()
    number_of_guests = models.IntegerField()
    booked =  models.BooleanField(default=False)

    def __str__(self):
        return f"Booking for {self.user.username} for {self.room}"

hotel/forms.py
from .models import Booking
from django import forms

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [ 'room','check_in_date',
                  'check_out_date','number_of_guests']
        
    def clean(self):
        cleaned_data = super().clean()
        check_in_date = cleaned_data.get('check_in_date')
        check_out_date = cleaned_data.get('check_out_date')

        if check_out_date <= check_in_date:
             raise forms.ValidationError("Check-out date must be after check-in date.")
        return cleaned_data

hotel/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Room, Hotel, Booking
from django.db import IntegrityError
from django.contrib import messages
from django.db.models import Q 

from .forms import BookingForm

# Create your views here.

def home_page(request):
    hotels =  Hotel.objects.all() 
    rooms =  Room.objects.all()    
    context = { 'hotels': hotels}

    return render(request, 'hotel/home.html', context)

def hotel_detail_page(request,slug):
    hotels = get_object_or_404(Hotel, slug=slug)
    rooms = Room.objects.filter(hotel=hotels)
    
    context = {'hotels':hotels,
               'background_image':hotels.background_image,
               'rooms':rooms
                }
    return render(request, 
                  'hotel/hotel_detail_page.html',
                  context)


def is_room_available(room,check_in_date,check_out_date):
    check_in_date = check_in_date
    check_out_date = check_out_date
    bookings = Booking.objects.filter(room=room)
    for booking in bookings:
        if booking.check_in_date < check_out_date and booking.check_out_date > check_in_date:
            if check_out_date < check_in_date:
                return False
            
            return False
    return True 

    
def check_booking_date(request):
    booking = Booking.objects.all()
    if booking.check_out_date < booking.check_in_date:
         messages.add_message(request, messages.ERROR, "Invalid dates added.") 
         print("Invalid date") 
         return False
    return True     
            


    
def book_a_room(request, slug):
    print('Booking')
    room = get_object_or_404(Room, slug=slug)
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            
            if is_room_available(room, form.cleaned_data['check_in_date'], form.cleaned_data['check_out_date']):
                
                try:
                    booking = form.save(commit=False)
                    booking.user = request.user
                    booking.room = room
                  
                    booking.save()
                    messages.add_message(request, messages.SUCCESS, "Room booked sucessfully.")
                    return redirect('hotel:home')
                   
                   
   
                except IntegrityError:
                    print("Can't book room. Database integrity error.")
                except Exception as e:
                    print(f"Can't book room. Error: {e}")
            else:
                 messages.add_message(request, messages.ERROR, "Room not available.")
                 print("Unavailable")
    else:
        form = BookingForm()
    context = {'room': room, 'form': form}
    return render(request, 'hotel/booking_form.html', context)
       
        


def search_for_room(request):
    if request.method == "POST":
        searched = request.POST['searched']
        searched = Room.objects.filter(name__icontains=searched)
        return render(request, 'hotel/searched_room.html' ,{'searched':searched})
        
    else:
        return render(request, 'hotel/searched_room.html')
    

hotel/templates/hotel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/tiny-slider/tiny-slider.css' %}">
    <link rel="stylesheet" href="{% static 'assets/glightbox/css/glightbox.css' %}">
    <link rel="stylesheet" href="{% static 'assets/choices/css/choices.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/flatpickr/css/flatpickr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-2.css' %}">
    
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'hotels:home' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'hotels:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" method="POST" action="{% url 'hotels:search_for_room' %}"
            name="searched"
            >
            {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search for Room" aria-label="Search" name="searched">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
          
        </div>

       
        {% if user.is_authenticated %}
        <p> Hello {{ user.username }}</p>
        {% else %}
            <a href="{% url 'login'  %}">Login</a> | <a href="{% url 'account:sign_up' %}">Sign up</a>
        {% endif %}
      </nav>



 
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/tiny-slider/tiny-slider.js' %}"></script>
    <script src="{% static 'assets/glightbox/js/glightbox.js' %}"></script>
    <script src="{% static 'assets/choices/js/choices.min.js' %}"></script>
    <script src="{% static 'assets/flatpickr/js/flatpickr.min.js' %}"></script>
</body>
</html>

hotel/templates/hotel/booking_form.html
{% extends "hotel/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>   
    {% endfor %}
{% endif %}

<div class="container">

    <form method='post'>
        {% csrf_token %}
        
        {{ form | crispy}}
        <button type='submit' class="btn btn-success">Book</button>
    
    </form>
</div>

{% endblock content %}

hotel/templates/hotel/home.html
{% extends "hotel/base.html" %}
{% load static %}
 

{% block title%} {% endblock title%}


{% block content %}
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>   
    {% endfor %}
{% endif %}

</div>

<div class="hero-section " >
    <div class="hero-text" >
        <h1>Choose Your Place To Stay</h1>
        <button class="btn btn-primary"> Book Now </button>
    </div>
</div>
    
<div class="hotel-display pt-3">
    <h2 class="text-center pt-5"> Choose a Hotel</h2>
</div>

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for hotel in hotels %}
        <div class="col">
          <div class="card shadow-sm">
            <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
                <img src="{{ hotel.image.url }}" class="img-fluid rounded " alt="">
            <div class="card-body">
              <p class="card-text">{{ hotel.name }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'hotels:hotel_detail'  hotel.slug %}" class="btn btn-primary">View Hotel</a>
                  
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>   
        {% endfor %}

      </div>
    </div>
  </div>



  

     
            
<!--  -->
        



{% endblock content %}

hotel/templates/hotel/hotel_detail_page.html
{% extends "hotel/base.html" %}

{% block content %}

<style>
    .detail-page{
        background-image: url({{ background_image }});
        background-size: cover;
        height:300px;
        filter: blur(1px);
        
        color: black;
    }

</style>
<div class="detail-page">
    <div class="hero-text text-center  text-bold" >
        <h1 class="">{{ hotels.name }}</h1>
        
    </div>
   
</div>
<h1 class="text-primary text-center mt-5"  > {{ hotels.name }} </h1>

<section class="container py-5">
    <div class="row">
        <div class="col-12 col-lg-6">
            <img src="{{ hotels.image.url }}" class="img-fluid rounded" alt="">
        </div>
        <div class="col-12 col-lg-6 mt-4">
            <h4 class="text-center">About this hotel</h4>
            <p>{{ hotels.description }}</p>
        </div>
    </div>
</section>



</section>
<section class="rooms container mt-5">
    <p class="text-center text-bold "> Our Amenities: </p>
    <hr>
    <div class="card-body pt-4 p-0">
        <div class="row g-4">
            <!-- Activities -->
            <div class="col-sm-6">
                <h6><i class="fa-solid fa-biking me-2"></i>Activities</h6>
                <!-- List -->
                 {% for activity in hotels.activities %}
                <ul class="list-group list-group-borderless mt-2 mb-0">
                    <li class="list-group-item pb-0">
                        <i class="fa-solid fa-check-circle text-success me-2"></i>{{ activity }}
                    </li>
                   
                </ul>
                {% endfor %}
            </div>

            <!-- Payment Method -->
            <div class="col-sm-6">
                <h6><i class="fa-solid fa-credit-card me-2"></i>Payment Method</h6>
                <!-- List -->
                 {% for payment in hotels.payment_method %}
                <ul class="list-group list-group-borderless mt-2 mb-0">
                    <li class="list-group-item pb-0">
                        <i class="fa-solid fa-check-circle text-success me-2"></i>{{ payment }}
                    </li>
                 
                </ul>
                {% endfor %}
            </div>

            <!-- Services -->
            <div class="col-sm-6">
                <h6><i class="fa-solid fa-concierge-bell me-2"></i>Services</h6>
                <!-- List -->
                 {% for service in hotels.services %}
                <ul class="list-group list-group-borderless mt-2 mb-0">
                    <li class="list-group-item pb-0">
                        <i class="fa-solid fa-check-circle text-success me-2"></i>{{ service }}
                    </li>
                    
                    
                </ul>
                {% endfor %}
            </div>

          

                <h6><i class="fa-solid fa-volume-up me-2"></i>Staff Language</h6>
                <!-- List -->
                 {% for language in hotels.staff_languages %}
                <ul class="list-group list-group-borderless mt-2 mb-0">
                    <li class="list-group-item pb-0">
                        <i class="fa-solid fa-check-circle text-success me-2"></i>{{ language }}
                    </li>
                    
                </ul>
                {% endfor %}
            </div>

        </div>
    </div>
    </a>

</section>




<!-- Featured Room -->
  <section>
	<div class="container">

		<!-- Title -->
		<div class="row mb-4">
			<div class="col-12 text-center">
				<h2 class="mb-0">Featured Rooms</h2>
			</div>
		</div>

		



<div class="card-body pt-4 p-0">
    <div class="vstack gap-4">

        <!-- Room item START -->
        {% for room in rooms %}
        <div class="card shadow p-3">
            <div class="row g-4">
                <!-- Card img -->
                <div class="col-md-5 position-relative">

                    <!-- Overlay item -->
                    <div class="position-absolute top-0 start-0 z-index-1 mt-3 ms-4">
                        <div class="badge text-bg-danger">30% Off</div>
                    </div>

                    <!-- Slider START -->
                    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                              <img src="{{ room.room_type.third_room_img.url }}" class="d-block w-100 img-fluid" alt="...">
                            </div>
                            <div class="carousel-item">
                              <img src="{{ room.room_type.third_room_img.url }}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                              <img src="{{ room.room_type.third_room_img.url }}" class="d-block w-100" alt="...">
                            </div>
                          </div>
                          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                    </div>
                    <!-- Slider END -->

                    <!-- Button -->
                    
                </div>

                <!-- Card body -->
                <div class="col-md-7">
                    <div class="card-body d-flex flex-column h-100 p-0">

                        <!-- Title -->
                        <h5 class="card-title"><a href="#">{{ room.name }}</a></h5>

                        <!-- Amenities -->
                         {% for room_option in room.room_options %}
                        <ul class="nav nav-divider mb-2">
                            <li class="nav-item">{{ room_option }}</li>
                            
                            
                        </ul>
                        {% endfor %}

                        
                        
                        <!-- Price and Button -->
                        <div class="d-sm-flex justify-content-sm-between align-items-center mt-auto">
                            <!-- Button -->
                            <div class="d-flex align-items-center">
                                <h5 class="fw-bold mb-0 me-1">${{ room.price }}</h5>
                                <span class="mb-0 me-2">/day</span>
                                <span class="text-decoration-line-through mb-0">$500</span>
                            </div>
                            <!-- Price -->
                            <div class="mt-3 mt-sm-0">
                                <a href="{% url 'hotels:book_a_room' room.slug %}" class="btn btn-sm btn-primary mb-0">Book Room</a>    
                                
                            </div>                  
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

        <!-- Room item END -->
    </div>
</div>
</section>



{% endblock content %}

hotel/templates/hotel/searched_room.html
{% extends "hotel/base.html" %}
{% load static %}

{% block content %}

<div class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>   
  {% endfor %}
{% endif %}
<center>
  <div class="container">
    {% if searched %}
      {% for room in searched %}
      <div class="card-body pt-4 p-0">
        <div class="vstack gap-4">
    
            <!-- Room item START -->
            
            <div class="card shadow p-3">
                <div class="row g-4">
                    <!-- Card img -->
                    <div class="col-md-5 position-relative">
    
                        <!-- Overlay item -->
                        <div class="position-absolute top-0 start-0 z-index-1 mt-3 ms-4">
                            <div class="badge text-bg-danger">30% Off</div>
                        </div>
    
                        <!-- Slider START -->
                        <div class="tiny-slider arrow-round arrow-xs arrow-dark overflow-hidden rounded-2">
                            <div class="tns-outer" id="tns1-ow"><div class="tns-liveregion tns-visually-hidden" aria-live="polite" aria-atomic="true">slide <span class="current">3</span>  of 4</div><div id="tns1-mw" class="tns-ovh"><div class="tns-inner" id="tns1-iw"><div class="tiny-slider-inner  tns-slider tns-carousel tns-subpixel tns-calc tns-horizontal" data-autoplay="true" data-arrow="true" data-dots="false" data-items="1" id="tns1" style="transform: translate3d(-33.3333%, 0px, 0px);"><div class="tns-item tns-slide-cloned" aria-hidden="true" tabindex="-1"><img src="assets/images/category/hotel/4by3/01.jpg" alt="Card image"></div>
                                <!-- Image item -->
                                <div class="tns-item" id="tns1-item0" aria-hidden="true" tabindex="-1"><img src="{{ room.room_type.third_room_img.url }}" class="img-fluid"   alt="Card image"></div>
    
                                <!-- Image item -->
                                <div class="tns-item tns-slide-active" id="tns1-item1"><img src="{{ room.room_type.third_room_img.url }}" class="img-fluid"  alt="Card image"></div>
    
                                <!-- Image item -->
                                <div class="tns-item" id="tns1-item2" aria-hidden="true" tabindex="-1"><img src="assets/images/category/hotel/4by3/03.jpg" alt="Card image"></div>
    
                                <!-- Image item -->
                                <div class="tns-item" id="tns1-item3" aria-hidden="true" tabindex="-1"><img src="assets/images/category/hotel/4by3/01.jpg" alt="Card image"></div>
                            <div class="tns-item tns-slide-cloned" aria-hidden="true" tabindex="-1"><img src="assets/images/category/hotel/4by3/04.jpg" alt="Card image"></div></div></div></div><div class="tns-controls" aria-label="Carousel Navigation" tabindex="0"><button type="button" data-controls="prev" tabindex="-1" aria-controls="tns1"><i class="bi bi-arrow-left"></i></button><button type="button" data-controls="next" tabindex="-1" aria-controls="tns1"><i class="bi bi-arrow-right"></i></button></div></div>
                        </div>
                        <!-- Slider END -->
    
                        <!-- Button -->
                        
                    </div>
    
                    <!-- Card body -->
                    <div class="col-md-7">
                        <div class="card-body d-flex flex-column h-100 p-0">
    
                            <!-- Title -->
                            <h5 class="card-title"><a href="#">{{ room.name }}</a></h5>
    
                            <!-- Amenities -->
                             {% for room_option in room.room_options %}
                            <ul class="nav nav-divider mb-2">
                                <li class="nav-item">{{ room_option }}</li>
                                
                                
                            </ul>
                            {% endfor %}
    
                            
                            
                            <!-- Price and Button -->
                            <div class="d-sm-flex justify-content-sm-between align-items-center mt-auto">
                                <!-- Button -->
                                <div class="d-flex align-items-center">
                                    <h5 class="fw-bold mb-0 me-1">${{ room.price }}</h5>
                                    <span class="mb-0 me-2">/day</span>
                                    <span class="text-decoration-line-through mb-0">$500</span>
                                </div>
                                <!-- Price -->
                                <div class="mt-3 mt-sm-0">
                                    <a href="{% url 'hotels:book_a_room' room.slug %}" class="btn btn-sm btn-primary mb-0">Book Room</a>    
                                </div>                  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
    
            <!-- Room item END -->
        </div>
    </div>
        
      {% endfor %}
    {% else %}
      <h2> Room does not exist </h2>
   
    {% endif %}
  </div>
</center>
{% endblock %}